Change run_connectivity to parallelize in 8 threads
azavea/pfb pull request #11
Opened 2017-02-01 21:09 UTC by sharph

## Overview

This splits out the "reachable" roads sql from one file (`reachable_roads_high_stress.sql`) into three files:

* `..._stress_prep.sql`
* `..._stress_run.sql`
* `..._stress_cleanup.sql`

the `_run.sql` file has `thread_num` and `thread_no` parameterized so that many instances of this sql can be run simultaneously. `run_connectivity.sh` now depends on `parallel` to run 8 instances simultaneously. This will require changes to the https://github.com/azavea/pfb-network-connectivity repo.

## Testing

* Run any analysis job as before
* Verify that the results table is identical
* Verify that the parallelized analysis runs in less time

Connects https://github.com/azavea/pfb-network-connectivity/issues/44

2017-02-01 21:18 UTC, sharph commented
I'm not sure of a great way to generate and pipe the `psql` commands into `parallel` without overengineering the process, short of listing the 8 commands as I have done in `run_connectivity.sh`. Let me know if you have any ideas.

2017-02-02 15:21 UTC, CloudNiner commented
So ideally we would probably wrap all these scripts in a SQL extension where the scripts are replaced with functions of the same name, so we can call the functions via psql and just do string substitution in the shell for variables rather than relying on the psql variables option. But I'm not sure that's worth the effort quite yet, most of the parameterization so far has been relatively simple. But its definitely not pretty as-is

For this case, can't run_connectivity take a `NUM_THREADS` env var and we loop to create the parallel command to run, rather than hardcoding eight?

2017-02-02 15:22 UTC, CloudNiner commented
Ran the analysis with this branch checked out and got this error:
```
/usr/bin/time: cannot run parallel: No such file or directory
Command exited with non-zero status 127
        Command being timed: "parallel"
...
```
Can you also submit a PR to the upstream repo that fixes our dev environment and ensures a parallelized run can proceed?

2017-02-02 16:30 UTC, sharph commented
PR submitted: https://github.com/azavea/pfb-network-connectivity/pull/53

2017-02-02 17:12 UTC, sharph commented
I can't think of a great way to do this in bash that isn't messier than the way I'm doing it now. I could write a helper script in python; that might be the least bad way to go about this even though it introduces another language into the mix.

I'm not sure how you would make this work in a SQL extension. There are other reasons we may not want to make this a SQL extension.

2017-02-02 17:50 UTC, CloudNiner commented
I think the parallelization is fine for now as is, although we'll definitely need to parameterize it somehow in the future. Let's make an issue for that.

2017-02-02 17:51 UTC, CloudNiner commented
Looks like the PFB performance spreadsheet you put together has a significant speedup in the `connected_census_blocks.sql`, but I don't see anything related to that here. Was that not included for some reason, or am I just misunderstanding?

2017-02-02 17:52 UTC, CloudNiner requested changes

2017-02-02 17:52 UTC, CloudNiner commented on run_connectivity.sh
> +/usr/bin/time -v psql -h "${NB_POSTGRESQL_HOST}" -U "${NB_POSTGRESQL_USER}" -d "${NB_POSTGRESQL_DB}" -f connectivity/reachable_roads_high_stress_clean.sql
Filename mismatch. Update here or change filenames of associated scripts.

2017-02-02 21:46 UTC, sharph commented on run_connectivity.sh
> +/usr/bin/time -v psql -h "${NB_POSTGRESQL_HOST}" -U "${NB_POSTGRESQL_USER}" -d "${NB_POSTGRESQL_DB}" -f connectivity/reachable_roads_high_stress_clean.sql
Addressed in https://github.com/azavea/pfb/pull/11/commits/db0cc4b708b81a2a59a55fae4e66eb946fd431a2

2017-02-02 21:49 UTC, sharph commented
I didn't mean to imply that I had measured `connected_census_blocks.sql` in the spreadsheet. The spreadsheet has been updated to clarify.

2017-02-02 21:51 UTC, sharph commented
Have issues been disabled for this project?

2017-02-03 13:39 UTC, CloudNiner commented on run_connectivity.sh
> +/usr/bin/time -v psql -h "${NB_POSTGRESQL_HOST}" -U "${NB_POSTGRESQL_USER}" -d "${NB_POSTGRESQL_DB}" -f connectivity/reachable_roads_high_stress_clean.sql
The filename is still wrong here. Both high and low stress filenames were mismatched.

2017-02-03 13:41 UTC, CloudNiner commented
Enabled issues. Thanks for clarifying the spreadsheet!

2017-02-03 15:58 UTC, sharph commented on run_connectivity.sh
> +/usr/bin/time -v psql -h "${NB_POSTGRESQL_HOST}" -U "${NB_POSTGRESQL_USER}" -d "${NB_POSTGRESQL_DB}" -f connectivity/reachable_roads_high_stress_clean.sql
Fixed in https://github.com/azavea/pfb/pull/11/commits/407d7bc9d331b54778e43ff763d684b53abc6a6d

2017-02-03 16:16 UTC, CloudNiner approved these changes
Was able to run the Boulder analysis successfully and output continues to be consistent with previous iterations after loading into QGIS.

2017-02-03 16:17 UTC, merged